### ISSUE TITLE
Cannot resolve "DaggerApplicationComponent"

### ISSUE THREAD

**Issue by abyd09** [BracketCove/RoomDemo2017#1]
I just tried your code, and found _DaggerApplicationComponent_ cannot be resolve, does it should be found in _roomdemo.wiseass.com.roomdemo.dependencyinjection.DaggerApplicationComponent_ ?

**Comment by abyd09** [comment]
Just tried Build -> Rebuild project then everything works

**Comment by BracketCove** [comment]
Glad to hear!
