### ISSUE TITLE
Where is DaggerApplicationComponent class

### ISSUE THREAD

**Issue by joniltonsilva** [BracketCove/RoomDemo2017#4]
Hi, i'm not find DaggerApplicationComponent in packages.

**Comment by manusoft** [comment]
Hi @joniltonsilva, you have to **make** the project. You'll find the option in **Build menu**. This class is created automatically by Dagger and does not exist until you make or build the project for the first time.

**Comment by BracketCove** [comment]
Thanks for answering manusoft; appreciated!
