### ISSUE TITLE
Curious use of static for addFragmentToActivity() within BaseActivity

### ISSUE THREAD

**Issue by ruairimcguigan** [BracketCove/RoomDemo2017#5]
Was wondering if you had any specific reason for making the addFragmentToActivity() static - if, as it seems, it's use was always be inherited by child Activities

**Comment by BezMan** [comment]
sent a pull request for this now as well.

**Comment by BracketCove** [comment]
Was a mistake; pull request accepted. Thanks for bringing this up!
